services:
  db:
    image: postgres:16
    container_name: threedex
    restart: always
    environment:
      POSTGRES_USER: threedex
      POSTGRES_PASSWORD: "3Dex!"
      POSTGRES_DB: threedex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/backend
    container_name: 3dex-api
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && node dist/src/server.js"

  minio:
    image: quay.io/minio/minio
    container_name: 3dex-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata:
