name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install & Build (On GitHub Runner)
        run: |
          npm install
          npx prisma generate --schema=apps/backend/prisma/schema.prisma
          npm run build --workspaces

      - name: Rsync Build Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # List the folders/files you actually need to run the app
          source: "apps/backend/dist/,apps/backend/package.json,apps/backend/prisma/,apps/frontend/.next/,apps/frontend/package.json,apps/frontend/public/,apps/frontend/next.config.ts,package.json,package-lock.json,ecosystem.config.js"
          target: "~/3Dex"

      - name: Finalize on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use --lts

            cd ~/3Dex
            # Only install production dependencies to save RAM
            npm install --omit=dev
            cd apps/backend
            npx prisma migrate deploy
            cd ../..
            pm2 reload ecosystem.config.js
